/*
 * generated by Xtext 2.17.1
 */
package org.caph.parser.tests

import com.google.inject.Inject
import org.caph.parser.caph.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(CaphInjectorProvider)
class CaphParsingTest {
	@Inject
	ParseHelper<Model> parseHelper

	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello xtext !
		''')
		Assert.assertNotNull(result)
		println(result)
		val errors = result.eResource.errors
		println(errors)
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
